# -*- coding: utf-8 -*-
"""MoNA (Management of Natural & Anthropogenic risks)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dsEWNk0BL8NE5SJ7Hu279nHTIAyMXGKf
"""

import streamlit as st
import pandas as pd
import datetime

# ------------------ APP CONFIG ------------------
st.set_page_config(page_title="MoNA — Management of Natural & Anthropogenic Risks", layout="wide")

# ------------------ HEADER ------------------
st.title("🌐 MoNA — Management of Natural & Anthropogenic Risks")
st.subheader("Your Continuous Risk Intelligence & Action Platform")

st.markdown(
    """
MoNA is designed to **monitor, audit, and mitigate both natural and man-made risks** across communities.
It enables **governments, NGOs, and citizens** to collaboratively ensure safer, equitable, and resilient cities.
"""
)

# ------------------ SIDEBAR ------------------
st.sidebar.title("Navigation")
page = st.sidebar.radio("Go to:", [
    "Dashboard",
    "Heatmap",
    "Risk Reports",
    "Predictive Alerts",
    "Resource & Budget Modeling"
])

# ------------------ DATA PLACEHOLDERS ------------------
dummy_data = pd.DataFrame({
    "Location": ["Ward 1", "Ward 2", "Ward 3"],
    "Risk Type": ["Flood Risk", "Waste Accumulation", "Structural Damage"],
    "Risk Level": ["High", "Medium", "Low"],
    "Key Issue": ["Drainage Blockage", "Unmanaged Garbage", "Cracked Bridge"],
    "Reported On": [datetime.date.today()] * 3
})

# ------------------ PAGE LOGIC ------------------
if page == "Dashboard":
    st.header("📊 Risk Intelligence Dashboard")
    st.markdown(
        """
**MoNA tracks and displays ongoing risks across:**
- 🌧️ **Natural Hazards** – flood, drought, extreme weather
- 🏙️ **Anthropogenic Hazards** – waste mismanagement, unsafe infrastructure
- 👩‍👩‍👧 **Gender & Vulnerable Groups** – prioritizes safe rehabilitation & resources for women, elderly, disabled
"""
    )
    st.dataframe(dummy_data)

elif page == "Heatmap":
    st.header("🗺️ Civic & Disaster Risk Heatmap")
    st.markdown(
        """
Visualizes reported issues and vulnerabilities across wards or districts.
_**Feature Placeholder:** Interactive heatmap with severity-based color coding._
"""
    )

elif page == "Risk Reports":
    st.header("📝 Risk Reports & Government Action Triggers")
    st.markdown(
        """
- Generate **automated risk audit reports**
- Provide **real-time summaries** to local authorities
- Track **response timelines** and highlight delays
- Promote **women-led committees** to oversee DRR actions
"""
    )
    st.download_button(
        "⬇️ Download Sample Risk Report",
        data=dummy_data.to_csv(index=False).encode("utf-8"),
        file_name="mona_risk_report.csv",
        mime="text/csv"
    )

elif page == "Predictive Alerts":
    st.header("🔔 Predictive Alerts & Early Warning System")
    st.markdown(
        """
Using **historical weather data, urban risk logs, and trend analysis**, MoNA will:
- Forecast upcoming **flood-prone periods**
- Predict **man-made risk spikes** (like waste overflow, road collapse risk)
- Send **proactive alerts** to stakeholders

_**Feature Placeholder:** AI/ML model outputs will be displayed here._
"""
    )

elif page == "Resource & Budget Modeling":
    st.header("⚖️ Resource & Budget Optimization")
    st.markdown(
        """
This module will simulate:
- Resource **demand vs. supply** during crisis
- Budget utilization and **remaining funds**
- Optimal **allocation strategy** to minimize future risks

_**Feature Placeholder:** Interactive system dynamics model will be here._
"""
    )

# ------------------ FOOTER ------------------
st.markdown("---")
st.caption("MoNA © 2025 | Management of Natural & Anthropogenic Risks | Built with ❤️ by Aakanksha Tiwari")