# -*- coding: utf-8 -*-
"""MoNA (Management of Natural & Anthropogenic risks)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dsEWNk0BL8NE5SJ7Hu279nHTIAyMXGKf
"""

import streamlit as st
import pandas as pd
import numpy as np
import datetime

# ------------------ APP CONFIG ------------------
st.set_page_config(page_title="MoNA — Management of Natural & Anthropogenic Risks", layout="wide")

# ------------------ HEADER ------------------
st.title("🌐 MoNA — Management of Natural & Anthropogenic Risks")
st.subheader("Your Continuous Risk Intelligence & Action Platform")

st.markdown("""
MoNA is designed to **monitor, audit, and mitigate both natural and man-made risks** across communities.
It enables **governments, NGOs, and citizens** to collaboratively ensure safer, equitable, and resilient cities.
""")

# ------------------ SIDEBAR ------------------
st.sidebar.title("Navigation")
page = st.sidebar.radio("Go to:", [
    "Dashboard",
    "Heatmap",
    "Risk Reports",
    "Predictive Alerts",
    "Resource & Budget Modeling"
])

# ------------------ DATA PLACEHOLDERS ------------------
# Replace with real data sources later (Govt APIs, historical logs, reports)
dummy_data = pd.DataFrame({
    "Location": ["Ward 1", "Ward 2", "Ward 3"],
    "Risk Type": ["Flood Risk", "Waste Accumulation", "Structural Damage"],
    "Risk Level": ["High", "Medium", "Low"],
    "Key Issue": ["Drainage Blockage", "Unmanaged Garbage", "Cracked Bridge"],
    "Reported On": [datetime.date.today()] * 3
})

# ------------------ PAGE LOGIC ------------------
if page == "Dashboard":
    st.header("📊 Risk Intelligence Dashboard")
    st.markdown("""
    **MoNA tracks and displays ongoing risks across:**
    - 🌧️ **Natural Hazards** – flood, drought, extreme weather
    - 🏙️ **Anthropogenic Hazards** – waste mismanageme